### ISSUE TITLE
Deprecated `licenses` in `package.json`

### ISSUE THREAD

**Issue by fczbkk** [AndreasPizsa/grunt-update-json#23]
File `package.json` contains field `licenses`, which is deprecated (see [https://docs.npmjs.com/files/package.json](https://docs.npmjs.com/files/package.json) for more info). This causes problems when running in newer versions of NodeJS (tested in `v4`):

```
Running "update_json" task
Warning: Invalid reference token: licenses Use --force to continue.

Aborted due to warnings.
```

Simply removing the `licenses` field and keeping the `license` field will do the trick.

**Comment by AndreasPizsa** [comment]
@fczbkk Just merged and published to npm. Thanks!
